server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: ${OSS-ACCESS-KEY}
      secret-key: ${OSS-SECRET-KEY}
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-acmdy
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appcode: ${SMS-APPCODE}

  application:
    name: gulimall-third-party
  elasticsearch:
    rest:
      uris: http://192.168.56.10:9200 # 改为你的ES实际端口
